package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupActivityCards<M extends BaseGroupActivityCards<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}

	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setIsUsed(java.lang.String isUsed) {
		set("is_used", isUsed);
	}

	public java.lang.String getIsUsed() {
		return get("is_used");
	}

	public void setUseTime(java.util.Date useTime) {
		set("use_time", useTime);
	}

	public java.util.Date getUseTime() {
		return get("use_time");
	}

	public void setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
	}

	public java.lang.Integer getMemberId() {
		return get("member_id");
	}

	public void setGroupActivityId(java.lang.Integer groupActivityId) {
		set("group_activity_id", groupActivityId);
	}

	public java.lang.Integer getGroupActivityId() {
		return get("group_activity_id");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

}
