package com.eshop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("address", "id", Address.class);
		arp.addMapping("advertisement", "id", Advertisement.class);
		arp.addMapping("audit_price", "id", AuditPrice.class);
		arp.addMapping("audit_price_items", "id", AuditPriceItems.class);
		arp.addMapping("audit_record", "id", AuditRecord.class);
		arp.addMapping("back", "id", Back.class);
		arp.addMapping("bank_card", "id", BankCard.class);
		arp.addMapping("big_orders", "id", BigOrders.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("collection", "id", Collection.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("coupon_product", "id", CouponProduct.class);
		arp.addMapping("customer", "id", Customer.class);
		arp.addMapping("customer_coupon", "id", CustomerCoupon.class);
		arp.addMapping("customer_gold", "id", CustomerGold.class);
		arp.addMapping("customer_grade", "id", CustomerGrade.class);
		arp.addMapping("customer_growth", "id", CustomerGrowth.class);
		arp.addMapping("customer_look_record", "id", CustomerLookRecord.class);
		arp.addMapping("customer_point", "id", CustomerPoint.class);
		arp.addMapping("customer_point_rule", "id", CustomerPointRule.class);
		arp.addMapping("customer_visit", "id", CustomerVisit.class);
		arp.addMapping("eletronic_invoice", "id", EletronicInvoice.class);
		arp.addMapping("group_activities", "id", GroupActivities.class);
		arp.addMapping("group_activity_cards", "id", GroupActivityCards.class);
		arp.addMapping("group_set_meal_products", "id", GroupSetMealProducts.class);
		arp.addMapping("group_set_meals", "id", GroupSetMeals.class);
		arp.addMapping("help_link", "id", HelpLink.class);
		arp.addMapping("invoice_record", "id", InvoiceRecord.class);
		arp.addMapping("ip_record", "id", IpRecord.class);
		arp.addMapping("log_record", "id", LogRecord.class);
		arp.addMapping("login_record", "id", LoginRecord.class);
		arp.addMapping("logistics_template", "id", LogisticsTemplate.class);
		arp.addMapping("logistics_template_detail", "id", LogisticsTemplateDetail.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("operation_log", "id", OperationLog.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_invoice", "id", OrderInvoice.class);
		arp.addMapping("pay_rate", "id", PayRate.class);
		arp.addMapping("pickup_address", "id", PickupAddress.class);
		arp.addMapping("plain_invoice", "id", PlainInvoice.class);
		arp.addMapping("point_product", "id", PointProduct.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("product_brand", "id", ProductBrand.class);
		arp.addMapping("product_hotel", "id", ProductHotel.class);
		arp.addMapping("product_order", "id", ProductOrder.class);
		arp.addMapping("product_pickup_address", "id", ProductPickupAddress.class);
		arp.addMapping("product_price", "id", ProductPrice.class);
		arp.addMapping("product_review", "id", ProductReview.class);
		arp.addMapping("promotion", "id", Promotion.class);
		arp.addMapping("promotion_baoyou", "id", PromotionBaoyou.class);
		arp.addMapping("promotion_condition", "id", PromotionCondition.class);
		arp.addMapping("promotion_dazhe", "id", PromotionDazhe.class);
		arp.addMapping("promotion_kanjia", "id", PromotionKanjia.class);
		arp.addMapping("promotion_manjian", "id", PromotionManjian.class);
		arp.addMapping("promotion_mansong", "id", PromotionMansong.class);
		arp.addMapping("promotion_miaosha", "id", PromotionMiaosha.class);
		arp.addMapping("promotion_pingtuan", "id", PromotionPingtuan.class);
		arp.addMapping("promotion_sku", "id", PromotionSku.class);
		arp.addMapping("property", "id", Property.class);
		arp.addMapping("property_value", "id", PropertyValue.class);
		arp.addMapping("recommend", "id", Recommend.class);
		arp.addMapping("recommend_position", "id", RecommendPosition.class);
		arp.addMapping("refund", "id", Refund.class);
		arp.addMapping("request_log", "id", RequestLog.class);
		arp.addMapping("resource", "id", Resource.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_navigation", "id", RoleNavigation.class);
		arp.addMapping("s_city", "id", SCity.class);
		arp.addMapping("s_district", "id", SDistrict.class);
		arp.addMapping("s_province", "id", SProvince.class);
		arp.addMapping("searchword", "id", Searchword.class);
		arp.addMapping("shop", "id", Shop.class);
		arp.addMapping("shop_decoration_module", "id", ShopDecorationModule.class);
		arp.addMapping("shopping_cart", "id", ShoppingCart.class);
		arp.addMapping("supplier", "id", Supplier.class);
		arp.addMapping("supplier_bill", "id", SupplierBill.class);
		arp.addMapping("supplier_bill_item", "id", SupplierBillItem.class);
		arp.addMapping("supplier_contract", "id", SupplierContract.class);
		arp.addMapping("supplier_period", "id", SupplierPeriod.class);
		arp.addMapping("tax", "id", Tax.class);
		arp.addMapping("user", "id", User.class);
		// Composite Primary Key order: role_id,user_id
		arp.addMapping("user_role", "role_id,user_id", UserRole.class);
		arp.addMapping("vat_invoice", "id", VatInvoice.class);
		arp.addMapping("vat_invoice_item", "id", VatInvoiceItem.class);
		arp.addMapping("wallet", "id", Wallet.class);
		arp.addMapping("withdraw_cash", "id", WithdrawCash.class);
	}
}

