package com.eshop.model;

import com.eshop.model.base.BaseAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Address extends BaseAddress<Address> {
	public static final Address dao = new Address();
}
