package com.eshop.model;

import com.eshop.model.base.BaseAdvertisement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advertisement extends BaseAdvertisement<Advertisement> {
	public static final Advertisement dao = new Advertisement();
}
