package com.eshop.model;

import com.eshop.model.base.BaseAuditPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuditPrice extends BaseAuditPrice<AuditPrice> {
	public static final AuditPrice dao = new AuditPrice();
}
