package com.eshop.model;

import com.eshop.model.base.BaseAuditPriceItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuditPriceItems extends BaseAuditPriceItems<AuditPriceItems> {
	public static final AuditPriceItems dao = new AuditPriceItems();
}
