package com.eshop.model;

import com.eshop.model.base.BaseAuditRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuditRecord extends BaseAuditRecord<AuditRecord> {
	public static final AuditRecord dao = new AuditRecord();
}
