package com.eshop.model;

import com.eshop.model.base.BaseBack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Back extends BaseBack<Back> {
	public static final Back dao = new Back();
}
