package com.eshop.model;

import com.eshop.model.base.BaseBankCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankCard extends BaseBankCard<BankCard> {
	public static final BankCard dao = new BankCard();
}
