package com.eshop.model;

import com.eshop.model.base.BaseCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collection extends BaseCollection<Collection> {
	public static final Collection dao = new Collection();
}
