package com.eshop.model;

import com.eshop.model.base.BaseCouponProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponProduct extends BaseCouponProduct<CouponProduct> {
	public static final CouponProduct dao = new CouponProduct();
}
