package com.eshop.model;

import com.eshop.model.base.BaseCustomerLookRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerLookRecord extends BaseCustomerLookRecord<CustomerLookRecord> {
	public static final CustomerLookRecord dao = new CustomerLookRecord();
}
