package com.eshop.model;

import com.eshop.model.base.BaseCustomerPoint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerPoint extends BaseCustomerPoint<CustomerPoint> {
	public static final CustomerPoint dao = new CustomerPoint();
}
