package com.eshop.model;

import com.eshop.model.base.BaseCustomerCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerCoupon extends BaseCustomerCoupon<CustomerCoupon> {
	public static final CustomerCoupon dao = new CustomerCoupon();
}
