package com.eshop.model;

import com.eshop.model.base.BaseCustomerPointRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerPointRule extends BaseCustomerPointRule<CustomerPointRule> {
	public static final CustomerPointRule dao = new CustomerPointRule();
}
