package com.eshop.model;

import com.eshop.model.base.BaseCustomerGold;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerGold extends BaseCustomerGold<CustomerGold> {
	public static final CustomerGold dao = new CustomerGold();
}
