package com.eshop.model;

import com.eshop.model.base.BaseGroupSetMealProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupSetMealProducts extends BaseGroupSetMealProducts<GroupSetMealProducts> {
	public static final GroupSetMealProducts dao = new GroupSetMealProducts();
}
