package com.eshop.model;

import com.eshop.model.base.BaseGroupSetMeals;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupSetMeals extends BaseGroupSetMeals<GroupSetMeals> {
	public static final GroupSetMeals dao = new GroupSetMeals();
}
