package com.eshop.model;

import com.eshop.model.base.BaseGroupActivityCards;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupActivityCards extends BaseGroupActivityCards<GroupActivityCards> {
	public static final GroupActivityCards dao = new GroupActivityCards();
}
