package com.eshop.model;

import com.eshop.model.base.BaseGroupActivities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupActivities extends BaseGroupActivities<GroupActivities> {
	public static final GroupActivities dao = new GroupActivities();
}
