package com.eshop.model;

import com.eshop.model.base.BaseIpRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpRecord extends BaseIpRecord<IpRecord> {
	public static final IpRecord dao = new IpRecord();
}
