package com.eshop.model;

import com.eshop.model.base.BaseLogisticsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsTemplate extends BaseLogisticsTemplate<LogisticsTemplate> {
	public static final LogisticsTemplate dao = new LogisticsTemplate();
}
