package com.eshop.model;

import com.eshop.model.base.BaseLogisticsTemplateDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsTemplateDetail extends BaseLogisticsTemplateDetail<LogisticsTemplateDetail> {
	public static final LogisticsTemplateDetail dao = new LogisticsTemplateDetail();
}
