package com.eshop.model;

import com.eshop.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order();
	
	public Order() {
		this.setGold(0);
	}
}
