package com.eshop.model;

import com.eshop.model.base.BasePayRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayRate extends BasePayRate<PayRate> {
	public static final PayRate dao = new PayRate();
}
