package com.eshop.model;

import com.eshop.model.base.BasePickupAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PickupAddress extends BasePickupAddress<PickupAddress> {
	public static final PickupAddress dao = new PickupAddress();
}
