package com.eshop.model;

import com.eshop.model.base.BaseProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();
}
