package com.eshop.model;

import com.eshop.model.base.BaseProductOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductOrder extends BaseProductOrder<ProductOrder> {
	public static final ProductOrder dao = new ProductOrder();
}
