package com.eshop.model;

import com.eshop.model.base.BaseProductReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductReview extends BaseProductReview<ProductReview> {
	public static final ProductReview dao = new ProductReview();
}
