package com.eshop.model;

import com.eshop.model.base.BaseProductBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductBrand extends BaseProductBrand<ProductBrand> {
	public static final ProductBrand dao = new ProductBrand();
}
