package com.eshop.model;

import com.eshop.model.base.BasePromotionSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionSku extends BasePromotionSku<PromotionSku> {
	public static final PromotionSku dao = new PromotionSku();
}
