package com.eshop.model;

import com.eshop.model.base.BasePromotionBaoyou;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionBaoyou extends BasePromotionBaoyou<PromotionBaoyou> {
	public static final PromotionBaoyou dao = new PromotionBaoyou();
}
