package com.eshop.model;

import com.eshop.model.base.BasePromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Promotion extends BasePromotion<Promotion> {
	public static final Promotion dao = new Promotion();
}
