package com.eshop.model;

import com.eshop.model.base.BasePromotionMiaosha;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionMiaosha extends BasePromotionMiaosha<PromotionMiaosha> {
	public static final PromotionMiaosha dao = new PromotionMiaosha();
}
