package com.eshop.model;

import com.eshop.model.base.BasePromotionManjian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionManjian extends BasePromotionManjian<PromotionManjian> {
	public static final PromotionManjian dao = new PromotionManjian();
}
