package com.eshop.model;

import com.eshop.model.base.BaseProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Property extends BaseProperty<Property> {
	public static final Property dao = new Property();
}
