package com.eshop.model;

import com.eshop.model.base.BaseRequestLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RequestLog extends BaseRequestLog<RequestLog> {
	public static final RequestLog dao = new RequestLog();
}
