package com.eshop.model;

import com.eshop.model.base.BaseRoleNavigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleNavigation extends BaseRoleNavigation<RoleNavigation> {
	public static final RoleNavigation dao = new RoleNavigation();
}
