package com.eshop.model;

import com.eshop.model.base.BaseSCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SCity extends BaseSCity<SCity> {
	public static final SCity dao = new SCity();
}
