package com.eshop.model;

import com.eshop.model.base.BaseSDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SDistrict extends BaseSDistrict<SDistrict> {
	public static final SDistrict dao = new SDistrict();
}
