package com.eshop.model;

import com.eshop.model.base.BaseSearchword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Searchword extends BaseSearchword<Searchword> {
	public static final Searchword dao = new Searchword();
}
