package com.eshop.model;

import com.eshop.model.base.BaseShoppingCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingCart extends BaseShoppingCart<ShoppingCart> {
	public static final ShoppingCart dao = new ShoppingCart();
}
