package com.eshop.model;

import com.eshop.model.base.BaseShopDecorationModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopDecorationModule extends BaseShopDecorationModule<ShopDecorationModule> {
	public static final ShopDecorationModule dao = new ShopDecorationModule();
}
