package com.eshop.model;

import com.eshop.model.base.BaseShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop();
}
