package com.eshop.model;

import com.eshop.model.base.BaseSupplierBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierBill extends BaseSupplierBill<SupplierBill> {
	public static final SupplierBill dao = new SupplierBill();
}
