package com.eshop.model;

import com.eshop.model.base.BaseSupplierBillItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierBillItem extends BaseSupplierBillItem<SupplierBillItem> {
	public static final SupplierBillItem dao = new SupplierBillItem();
}
