package com.eshop.model;

import com.eshop.model.base.BaseVatInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VatInvoice extends BaseVatInvoice<VatInvoice> {
	public static final VatInvoice dao = new VatInvoice();
}
