package com.eshop.model;

import com.eshop.model.base.BasePromotionCondition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionCondition extends BasePromotionCondition<PromotionCondition> {
	public static final PromotionCondition dao = new PromotionCondition();
}
