package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRequestLog<M extends BaseRequestLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setRequestUrl(java.lang.String requestUrl) {
		set("request_url", requestUrl);
	}

	public java.lang.String getRequestUrl() {
		return get("request_url");
	}

	public void setRouteUrl(java.lang.String routeUrl) {
		set("route_url", routeUrl);
	}

	public java.lang.String getRouteUrl() {
		return get("route_url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
