package com.eshop.model;

import com.eshop.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource();
}
