package com.eshop.model;

import com.eshop.model.base.BaseEletronicInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EletronicInvoice extends BaseEletronicInvoice<EletronicInvoice> {
	public static final EletronicInvoice dao = new EletronicInvoice();
}
