package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setShopType(java.lang.Integer shopType) {
		set("shopType", shopType);
	}

	public java.lang.Integer getShopType() {
		return get("shopType");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}

	public java.lang.Integer getDistrictId() {
		return get("district_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public void setBusinessLicense(java.lang.String businessLicense) {
		set("businessLicense", businessLicense);
	}

	public java.lang.String getBusinessLicense() {
		return get("businessLicense");
	}

	public void setIdcardPic(java.lang.Integer idcardPic) {
		set("idcardPic", idcardPic);
	}

	public java.lang.Integer getIdcardPic() {
		return get("idcardPic");
	}

	public void setBusinessLicensePic(java.lang.Integer businessLicensePic) {
		set("businessLicensePic", businessLicensePic);
	}

	public java.lang.Integer getBusinessLicensePic() {
		return get("businessLicensePic");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLogoPic(java.lang.Integer logoPic) {
		set("logoPic", logoPic);
	}

	public java.lang.Integer getLogoPic() {
		return get("logoPic");
	}

	public void setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
	}

	public java.lang.Integer getCategoryId() {
		return get("category_id");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

}
