package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBack<M extends BaseBack<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setProductOrderId(java.lang.Integer productOrderId) {
		set("product_order_id", productOrderId);
	}

	public java.lang.Integer getProductOrderId() {
		return get("product_order_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setRefundAmount(java.lang.Integer refundAmount) {
		set("refundAmount", refundAmount);
	}

	public java.lang.Integer getRefundAmount() {
		return get("refundAmount");
	}

	public void setRefundCash(java.math.BigDecimal refundCash) {
		set("refundCash", refundCash);
	}

	public java.math.BigDecimal getRefundCash() {
		return get("refundCash");
	}

	public void setIsGeted(java.lang.Boolean isGeted) {
		set("isGeted", isGeted);
	}

	public java.lang.Boolean getIsGeted() {
		return get("isGeted");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setRefuseNote(java.lang.String refuseNote) {
		set("refuseNote", refuseNote);
	}

	public java.lang.String getRefuseNote() {
		return get("refuseNote");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

	public void setRefundCode(java.lang.String refundCode) {
		set("refund_code", refundCode);
	}

	public java.lang.String getRefundCode() {
		return get("refund_code");
	}

	public void setRemitTime(java.util.Date remitTime) {
		set("remitTime", remitTime);
	}

	public java.util.Date getRemitTime() {
		return get("remitTime");
	}

	public void setSuccessTime(java.util.Date successTime) {
		set("successTime", successTime);
	}

	public java.util.Date getSuccessTime() {
		return get("successTime");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setApplyCash(java.math.BigDecimal applyCash) {
		set("applyCash", applyCash);
	}

	public java.math.BigDecimal getApplyCash() {
		return get("applyCash");
	}

	public void setDeliveryPrice(java.math.BigDecimal deliveryPrice) {
		set("deliveryPrice", deliveryPrice);
	}

	public java.math.BigDecimal getDeliveryPrice() {
		return get("deliveryPrice");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("couponDiscount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("couponDiscount");
	}

}
