package com.eshop.model;

import com.eshop.model.base.BaseEletronicInvoiceItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EletronicInvoiceItem extends BaseEletronicInvoiceItem<EletronicInvoiceItem> {
	public static final EletronicInvoiceItem dao = new EletronicInvoiceItem();
}
