package com.eshop.model;

import com.eshop.model.base.BaseTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tax extends BaseTax<Tax> {
	public static final Tax dao = new Tax();
}
