package com.eshop.model;

import com.eshop.model.base.BaseWallet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wallet extends BaseWallet<Wallet> {
	public static final Wallet dao = new Wallet();
}
