package com.eshop.model;

import com.eshop.model.base.BaseProductPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductPrice extends BaseProductPrice<ProductPrice> {
	public static final ProductPrice dao = new ProductPrice();
}
