package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuditPrice<M extends BaseAuditPrice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setPriceId(java.lang.Integer priceId) {
		set("price_id", priceId);
	}

	public java.lang.Integer getPriceId() {
		return get("price_id");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
	}

	public java.lang.String getSupplierName() {
		return get("supplier_name");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setProperty(java.lang.String property) {
		set("property", property);
	}

	public java.lang.String getProperty() {
		return get("property");
	}

	public void setOldSuggestedRetailUnitPrice(java.math.BigDecimal oldSuggestedRetailUnitPrice) {
		set("oldSuggestedRetailUnitPrice", oldSuggestedRetailUnitPrice);
	}

	public java.math.BigDecimal getOldSuggestedRetailUnitPrice() {
		return get("oldSuggestedRetailUnitPrice");
	}

	public void setOldUnitCost(java.math.BigDecimal oldUnitCost) {
		set("oldUnitCost", oldUnitCost);
	}

	public java.math.BigDecimal getOldUnitCost() {
		return get("oldUnitCost");
	}

	public void setOldOriginUnitPrice(java.math.BigDecimal oldOriginUnitPrice) {
		set("oldOriginUnitPrice", oldOriginUnitPrice);
	}

	public java.math.BigDecimal getOldOriginUnitPrice() {
		return get("oldOriginUnitPrice");
	}

	public void setNewSuggestedRetailUnitPrice(java.math.BigDecimal newSuggestedRetailUnitPrice) {
		set("newSuggestedRetailUnitPrice", newSuggestedRetailUnitPrice);
	}

	public java.math.BigDecimal getNewSuggestedRetailUnitPrice() {
		return get("newSuggestedRetailUnitPrice");
	}

	public void setNewUnitCost(java.math.BigDecimal newUnitCost) {
		set("newUnitCost", newUnitCost);
	}

	public java.math.BigDecimal getNewUnitCost() {
		return get("newUnitCost");
	}

	public void setNewOriginUnitPrice(java.math.BigDecimal newOriginUnitPrice) {
		set("newOriginUnitPrice", newOriginUnitPrice);
	}

	public java.math.BigDecimal getNewOriginUnitPrice() {
		return get("newOriginUnitPrice");
	}

	public void setOldAmount(java.lang.Integer oldAmount) {
		set("oldAmount", oldAmount);
	}

	public java.lang.Integer getOldAmount() {
		return get("oldAmount");
	}

	public void setNewAmount(java.lang.Integer newAmount) {
		set("newAmount", newAmount);
	}

	public java.lang.Integer getNewAmount() {
		return get("newAmount");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setPublishStatus(java.lang.String publishStatus) {
		set("publish_status", publishStatus);
	}

	public java.lang.String getPublishStatus() {
		return get("publish_status");
	}

	public void setLastAuditTime(java.util.Date lastAuditTime) {
		set("last_audit_time", lastAuditTime);
	}

	public java.util.Date getLastAuditTime() {
		return get("last_audit_time");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}

	public java.lang.String getPublisher() {
		return get("publisher");
	}

	public void setShopName(java.lang.String shopName) {
		set("shop_name", shopName);
	}

	public java.lang.String getShopName() {
		return get("shop_name");
	}

	public void setTheSameNum(java.lang.Integer theSameNum) {
		set("theSameNum", theSameNum);
	}

	public java.lang.Integer getTheSameNum() {
		return get("theSameNum");
	}

}
