package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSProvince<M extends BaseSProvince<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDateCreated(java.util.Date DateCreated) {
		set("DateCreated", DateCreated);
	}

	public java.util.Date getDateCreated() {
		return get("DateCreated");
	}

	public void setDateUpdated(java.util.Date DateUpdated) {
		set("DateUpdated", DateUpdated);
	}

	public java.util.Date getDateUpdated() {
		return get("DateUpdated");
	}

}
