package com.eshop.model;

import com.eshop.model.base.BaseSupplierPeriod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierPeriod extends BaseSupplierPeriod<SupplierPeriod> {
	public static final SupplierPeriod dao = new SupplierPeriod();
}
