package com.eshop.model;

import com.eshop.model.base.BaseSProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SProvince extends BaseSProvince<SProvince> {
	public static final SProvince dao = new SProvince();
}
