package com.eshop.model;

import com.eshop.model.base.BaseOperationLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperationLog extends BaseOperationLog<OperationLog> {
	public static final OperationLog dao = new OperationLog();
}
