package com.eshop.model;

import com.eshop.model.base.BaseSupplierContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierContract extends BaseSupplierContract<SupplierContract> {
	public static final SupplierContract dao = new SupplierContract();
}
