package com.eshop.model;

import com.eshop.model.base.BaseOrderInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInvoice extends BaseOrderInvoice<OrderInvoice> {
	public static final OrderInvoice dao = new OrderInvoice();
}
