package com.eshop.model;

import com.eshop.model.base.BaseRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Refund extends BaseRefund<Refund> {
	public static final Refund dao = new Refund();
}
