package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEletronicInvoice<M extends BaseEletronicInvoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setInvoiceHead(java.lang.String invoiceHead) {
		set("invoiceHead", invoiceHead);
	}

	public java.lang.String getInvoiceHead() {
		return get("invoiceHead");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customerId");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
	}

	public java.lang.String getCompanyCode() {
		return get("companyCode");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setInvoiceContent(java.lang.Integer invoiceContent) {
		set("invoiceContent", invoiceContent);
	}

	public java.lang.Integer getInvoiceContent() {
		return get("invoiceContent");
	}

}
