package com.eshop.model;

import com.eshop.model.base.BaseProductPickupAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductPickupAddress extends BaseProductPickupAddress<ProductPickupAddress> {
	public static final ProductPickupAddress dao = new ProductPickupAddress();
}
