package com.eshop.model;

import com.eshop.model.base.BaseWithdrawCash;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WithdrawCash extends BaseWithdrawCash<WithdrawCash> {
	public static final WithdrawCash dao = new WithdrawCash();
}
