package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuditRecord<M extends BaseAuditRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTradeCode(java.lang.String tradeCode) {
		set("tradeCode", tradeCode);
	}

	public java.lang.String getTradeCode() {
		return get("tradeCode");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("tradeNo", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("tradeNo");
	}

	public void setTradeType(java.lang.Integer tradeType) {
		set("tradeType", tradeType);
	}

	public java.lang.Integer getTradeType() {
		return get("tradeType");
	}

	public void setPayable(java.math.BigDecimal payable) {
		set("payable", payable);
	}

	public java.math.BigDecimal getPayable() {
		return get("payable");
	}

	public void setThirdPayable(java.math.BigDecimal thirdPayable) {
		set("thirdPayable", thirdPayable);
	}

	public java.math.BigDecimal getThirdPayable() {
		return get("thirdPayable");
	}

	public void setTradeTime(java.util.Date tradeTime) {
		set("tradeTime", tradeTime);
	}

	public java.util.Date getTradeTime() {
		return get("tradeTime");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setDiffer(java.math.BigDecimal differ) {
		set("differ", differ);
	}

	public java.math.BigDecimal getDiffer() {
		return get("differ");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
