package com.eshop.model;

import com.eshop.model.base.BaseCustomerGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerGrade extends BaseCustomerGrade<CustomerGrade> {
	public static final CustomerGrade dao = new CustomerGrade();
}
