package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}

	public java.lang.Integer getDistrictId() {
		return get("district_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zipCode", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zipCode");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setDetailedAddress(java.lang.String detailedAddress) {
		set("detailedAddress", detailedAddress);
	}

	public java.lang.String getDetailedAddress() {
		return get("detailedAddress");
	}

	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setIsDefault(java.lang.Integer isDefault) {
		set("isDefault", isDefault);
	}

	public java.lang.Integer getIsDefault() {
		return get("isDefault");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setDistrict(java.lang.String district) {
		set("district", district);
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

}
