package com.eshop.model;

import com.eshop.model.base.BasePropertyValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyValue extends BasePropertyValue<PropertyValue> {
	public static final PropertyValue dao = new PropertyValue();
}
