package com.eshop.model;

import com.eshop.model.base.BaseLoginRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginRecord extends BaseLoginRecord<LoginRecord> {
	public static final LoginRecord dao = new LoginRecord();
}
