package com.eshop.model;

import com.eshop.model.base.BaseRecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommend extends BaseRecommend<Recommend> {
	public static final Recommend dao = new Recommend();
}
