package com.eshop.model;

import com.eshop.model.base.BaseCustomerVisit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerVisit extends BaseCustomerVisit<CustomerVisit> {
	public static final CustomerVisit dao = new CustomerVisit();
}
