package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWallet<M extends BaseWallet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setEvent(java.lang.Integer event) {
		set("event", event);
	}

	public java.lang.Integer getEvent() {
		return get("event");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setRelateId(java.lang.Integer relateId) {
		set("relate_id", relateId);
	}

	public java.lang.Integer getRelateId() {
		return get("relate_id");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finishTime", finishTime);
	}

	public java.util.Date getFinishTime() {
		return get("finishTime");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("tradeNo", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("tradeNo");
	}

	public void setIsPaySuccess(java.lang.Integer isPaySuccess) {
		set("isPaySuccess", isPaySuccess);
	}

	public java.lang.Integer getIsPaySuccess() {
		return get("isPaySuccess");
	}

	public void setTransactionId(java.lang.String transactionId) {
		set("transactionId", transactionId);
	}

	public java.lang.String getTransactionId() {
		return get("transactionId");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return get("source");
	}

}
