package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierContract<M extends BaseSupplierContract<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setAccountPeriod(java.lang.String accountPeriod) {
		set("account_period", accountPeriod);
	}

	public java.lang.String getAccountPeriod() {
		return get("account_period");
	}

	public void setContractFile(java.lang.String contractFile) {
		set("contract_file", contractFile);
	}

	public java.lang.String getContractFile() {
		return get("contract_file");
	}

	public void setStartAt(java.util.Date startAt) {
		set("start_at", startAt);
	}

	public java.util.Date getStartAt() {
		return get("start_at");
	}

	public void setEndAt(java.util.Date endAt) {
		set("end_at", endAt);
	}

	public java.util.Date getEndAt() {
		return get("end_at");
	}

}
