package com.eshop.model;

import com.eshop.model.base.BaseShopDecorationStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopDecorationStyle extends BaseShopDecorationStyle<ShopDecorationStyle> {
	public static final ShopDecorationStyle dao = new ShopDecorationStyle();
}
