package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionKanjia<M extends BasePromotionKanjia<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPromotionId(java.lang.Integer promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Integer getPromotionId() {
		return get("promotion_id");
	}

	public void setSum(java.lang.Integer sum) {
		set("sum", sum);
	}

	public java.lang.Integer getSum() {
		return get("sum");
	}

	public void setFavourable(java.lang.Integer favourable) {
		set("favourable", favourable);
	}

	public java.lang.Integer getFavourable() {
		return get("favourable");
	}

}
