package com.eshop.model;

import com.eshop.model.base.BasePlainInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlainInvoice extends BasePlainInvoice<PlainInvoice> {
	public static final PlainInvoice dao = new PlainInvoice();
}
