package com.eshop.model;

import com.eshop.model.base.BaseInvoiceRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvoiceRecord extends BaseInvoiceRecord<InvoiceRecord> {
	public static final InvoiceRecord dao = new InvoiceRecord();
}
