package com.eshop.model;

import com.eshop.model.base.BaseBigOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BigOrders extends BaseBigOrders<BigOrders> {
	public static final BigOrders dao = new BigOrders();
}
