package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setAddressId(java.lang.Integer addressId) {
		set("address_id", addressId);
	}

	public java.lang.Integer getAddressId() {
		return get("address_id");
	}

	public void setPromotionId(java.lang.Integer promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Integer getPromotionId() {
		return get("promotion_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return get("source");
	}

	public void setPreferredContactPhone(java.lang.String preferredContactPhone) {
		set("preferredContactPhone", preferredContactPhone);
	}

	public java.lang.String getPreferredContactPhone() {
		return get("preferredContactPhone");
	}

	public void setTotalPayable(java.math.BigDecimal totalPayable) {
		set("totalPayable", totalPayable);
	}

	public java.math.BigDecimal getTotalPayable() {
		return get("totalPayable");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("orderTime", orderTime);
	}

	public java.util.Date getOrderTime() {
		return get("orderTime");
	}

	public void setCompleteTime(java.util.Date completeTime) {
		set("completeTime", completeTime);
	}

	public java.util.Date getCompleteTime() {
		return get("completeTime");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}

	public java.lang.String getOrderCode() {
		return get("order_code");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setReceiveDetailAddress(java.lang.String receiveDetailAddress) {
		set("receiveDetailAddress", receiveDetailAddress);
	}

	public java.lang.String getReceiveDetailAddress() {
		return get("receiveDetailAddress");
	}

	public void setCancelReason(java.lang.String cancelReason) {
		set("cancel_reason", cancelReason);
	}

	public java.lang.String getCancelReason() {
		return get("cancel_reason");
	}

	public void setCancelNote(java.lang.String cancelNote) {
		set("cancel_note", cancelNote);
	}

	public java.lang.String getCancelNote() {
		return get("cancel_note");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

	public void setGold(java.lang.Integer gold) {
		set("gold", gold);
	}

	public java.lang.Integer getGold() {
		return get("gold");
	}

	public void setInvoiceHead(java.lang.String invoiceHead) {
		set("invoiceHead", invoiceHead);
	}

	public java.lang.String getInvoiceHead() {
		return get("invoiceHead");
	}

	public void setDeliveryPrice(java.math.BigDecimal deliveryPrice) {
		set("deliveryPrice", deliveryPrice);
	}

	public java.math.BigDecimal getDeliveryPrice() {
		return get("deliveryPrice");
	}

	public void setExpressCode(java.lang.String expressCode) {
		set("expressCode", expressCode);
	}

	public java.lang.String getExpressCode() {
		return get("expressCode");
	}

	public void setTheSameOrderNum(java.lang.String theSameOrderNum) {
		set("theSameOrderNum", theSameOrderNum);
	}

	public java.lang.String getTheSameOrderNum() {
		return get("theSameOrderNum");
	}

	public void setLogisticsName(java.lang.String logisticsName) {
		set("logisticsName", logisticsName);
	}

	public java.lang.String getLogisticsName() {
		return get("logisticsName");
	}

	public void setReceiveName(java.lang.String receiveName) {
		set("receiveName", receiveName);
	}

	public java.lang.String getReceiveName() {
		return get("receiveName");
	}

	public void setReceiveProvince(java.lang.String receiveProvince) {
		set("receiveProvince", receiveProvince);
	}

	public java.lang.String getReceiveProvince() {
		return get("receiveProvince");
	}

	public void setReceiveCity(java.lang.String receiveCity) {
		set("receiveCity", receiveCity);
	}

	public java.lang.String getReceiveCity() {
		return get("receiveCity");
	}

	public void setReceiveDistrict(java.lang.String receiveDistrict) {
		set("receiveDistrict", receiveDistrict);
	}

	public java.lang.String getReceiveDistrict() {
		return get("receiveDistrict");
	}

	public void setExpressSubscribeStatus(java.lang.Integer expressSubscribeStatus) {
		set("expressSubscribeStatus", expressSubscribeStatus);
	}

	public java.lang.Integer getExpressSubscribeStatus() {
		return get("expressSubscribeStatus");
	}

	public void setExpressDetail(java.lang.String expressDetail) {
		set("expressDetail", expressDetail);
	}

	public java.lang.String getExpressDetail() {
		return get("expressDetail");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("couponDiscount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("couponDiscount");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("tradeNo", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("tradeNo");
	}

	public void setCodeType(java.lang.Integer codeType) {
		set("codeType", codeType);
	}

	public java.lang.Integer getCodeType() {
		return get("codeType");
	}

	public void setPayTime(java.util.Date payTime) {
		set("payTime", payTime);
	}

	public java.util.Date getPayTime() {
		return get("payTime");
	}

	public void setSendOutTime(java.util.Date sendOutTime) {
		set("sendOutTime", sendOutTime);
	}

	public java.util.Date getSendOutTime() {
		return get("sendOutTime");
	}

	public void setReceiveTime(java.util.Date receiveTime) {
		set("receiveTime", receiveTime);
	}

	public java.util.Date getReceiveTime() {
		return get("receiveTime");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancelTime", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancelTime");
	}

	public void setPayRate(java.math.BigDecimal payRate) {
		set("payRate", payRate);
	}

	public java.math.BigDecimal getPayRate() {
		return get("payRate");
	}

	public void setPayRateSum(java.math.BigDecimal payRateSum) {
		set("payRateSum", payRateSum);
	}

	public java.math.BigDecimal getPayRateSum() {
		return get("payRateSum");
	}

	public void setCardType(java.lang.Integer cardType) {
		set("cardType", cardType);
	}

	public java.lang.Integer getCardType() {
		return get("cardType");
	}

	public void setShopName(java.lang.String shopName) {
		set("shopName", shopName);
	}

	public java.lang.String getShopName() {
		return get("shopName");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}

	public java.lang.String getSupplierName() {
		return get("supplierName");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setPromotionDiscount(java.math.BigDecimal promotionDiscount) {
		set("promotionDiscount", promotionDiscount);
	}

	public java.math.BigDecimal getPromotionDiscount() {
		return get("promotionDiscount");
	}

	public void setLogisticsNum(java.lang.String logisticsNum) {
		set("logisticsNum", logisticsNum);
	}

	public java.lang.String getLogisticsNum() {
		return get("logisticsNum");
	}

	public void setCouponId(java.lang.Integer couponId) {
		set("couponId", couponId);
	}

	public java.lang.Integer getCouponId() {
		return get("couponId");
	}

	public void setTotalProductCost(java.math.BigDecimal totalProductCost) {
		set("totalProductCost", totalProductCost);
	}

	public java.math.BigDecimal getTotalProductCost() {
		return get("totalProductCost");
	}

	public void setTotalActualProductPrice(java.math.BigDecimal totalActualProductPrice) {
		set("totalActualProductPrice", totalActualProductPrice);
	}

	public java.math.BigDecimal getTotalActualProductPrice() {
		return get("totalActualProductPrice");
	}

	public void setTaxRateSum(java.math.BigDecimal taxRateSum) {
		set("taxRateSum", taxRateSum);
	}

	public java.math.BigDecimal getTaxRateSum() {
		return get("taxRateSum");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}

	public java.lang.Integer getOrderType() {
		return get("order_type");
	}

	public void setPoints(java.lang.Integer points) {
		set("points", points);
	}

	public java.lang.Integer getPoints() {
		return get("points");
	}

}
