package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVatInvoice<M extends BaseVatInvoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customerId");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("companyName");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
	}

	public java.lang.String getCompanyCode() {
		return get("companyCode");
	}

	public void setCompanyAddress(java.lang.String companyAddress) {
		set("companyAddress", companyAddress);
	}

	public java.lang.String getCompanyAddress() {
		return get("companyAddress");
	}

	public void setCompanyPhone(java.lang.String companyPhone) {
		set("companyPhone", companyPhone);
	}

	public java.lang.String getCompanyPhone() {
		return get("companyPhone");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bankAccount", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return get("bankAccount");
	}

	public void setInvoiceContent(java.lang.Integer invoiceContent) {
		set("invoiceContent", invoiceContent);
	}

	public java.lang.Integer getInvoiceContent() {
		return get("invoiceContent");
	}

}
