package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public void setDob(java.util.Date dob) {
		set("dob", dob);
	}

	public java.util.Date getDob() {
		return get("dob");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setMobilePhone(java.lang.String mobilePhone) {
		set("mobilePhone", mobilePhone);
	}

	public java.lang.String getMobilePhone() {
		return get("mobilePhone");
	}

	public void setWeiXinOpenId(java.lang.String weiXinOpenId) {
		set("weiXinOpenId", weiXinOpenId);
	}

	public java.lang.String getWeiXinOpenId() {
		return get("weiXinOpenId");
	}

	public void setQqOpenId(java.lang.String qqOpenId) {
		set("qqOpenId", qqOpenId);
	}

	public java.lang.String getQqOpenId() {
		return get("qqOpenId");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("headImg");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}

	public java.lang.String getNickName() {
		return get("nickName");
	}

	public void setDisable(java.lang.Integer disable) {
		set("disable", disable);
	}

	public java.lang.Integer getDisable() {
		return get("disable");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public void setBalancePwd(java.lang.String balancePwd) {
		set("balancePwd", balancePwd);
	}

	public java.lang.String getBalancePwd() {
		return get("balancePwd");
	}

	public void setPoints(java.lang.Integer points) {
		set("points", points);
	}

	public java.lang.Integer getPoints() {
		return get("points");
	}

	public void setGolds(java.lang.Integer golds) {
		set("golds", golds);
	}

	public java.lang.Integer getGolds() {
		return get("golds");
	}

	public void setGrowths(java.lang.Integer growths) {
		set("growths", growths);
	}

	public java.lang.Integer getGrowths() {
		return get("growths");
	}

	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}

	public java.lang.String getGrade() {
		return get("grade");
	}

}
