package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecommend<M extends BaseRecommend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRecommendpositionId(java.lang.Integer recommendpositionId) {
		set("recommendPosition_id", recommendpositionId);
	}

	public java.lang.Integer getRecommendpositionId() {
		return get("recommendPosition_id");
	}

	public void setSortNumber(java.lang.Integer sortNumber) {
		set("sortNumber", sortNumber);
	}

	public java.lang.Integer getSortNumber() {
		return get("sortNumber");
	}

	public void setRelateId(java.lang.Integer relateId) {
		set("relate_Id", relateId);
	}

	public java.lang.Integer getRelateId() {
		return get("relate_Id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setRecommendPic(java.lang.Integer recommendPic) {
		set("recommendPic", recommendPic);
	}

	public java.lang.Integer getRecommendPic() {
		return get("recommendPic");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setRecommendPositionName(java.lang.String recommendPositionName) {
		set("recommendPositionName", recommendPositionName);
	}

	public java.lang.String getRecommendPositionName() {
		return get("recommendPositionName");
	}

}
