package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopDecorationStyle<M extends BaseShopDecorationStyle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

	public void setPageType(java.lang.Integer pageType) {
		set("pageType", pageType);
	}

	public java.lang.Integer getPageType() {
		return get("pageType");
	}

	public void setBackgroundColor(java.lang.String backgroundColor) {
		set("backgroundColor", backgroundColor);
	}

	public java.lang.String getBackgroundColor() {
		return get("backgroundColor");
	}

	public void setBackgroundImage(java.lang.String backgroundImage) {
		set("backgroundImage", backgroundImage);
	}

	public java.lang.String getBackgroundImage() {
		return get("backgroundImage");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
