package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerGrade<M extends BaseCustomerGrade<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setStart(java.lang.Integer start) {
		set("start", start);
	}

	public java.lang.Integer getStart() {
		return get("start");
	}

	public void setEnd(java.lang.Integer end) {
		set("end", end);
	}

	public java.lang.Integer getEnd() {
		return get("end");
	}

	public void setVip(java.lang.Integer vip) {
		set("vip", vip);
	}

	public java.lang.Integer getVip() {
		return get("vip");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
