package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionDazhe<M extends BasePromotionDazhe<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFull(java.math.BigDecimal full) {
		set("full", full);
	}

	public java.math.BigDecimal getFull() {
		return get("full");
	}

	public void setValue(java.math.BigDecimal value) {
		set("value", value);
	}

	public java.math.BigDecimal getValue() {
		return get("value");
	}

	public void setPromotionId(java.lang.Integer promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Integer getPromotionId() {
		return get("promotion_id");
	}

}
