package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStartDate(java.util.Date startDate) {
		set("startDate", startDate);
	}

	public java.util.Date getStartDate() {
		return get("startDate");
	}

	public void setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
	}

	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public void setBaseOn(java.lang.Integer baseOn) {
		set("baseOn", baseOn);
	}

	public java.lang.Integer getBaseOn() {
		return get("baseOn");
	}

	public void setScope(java.lang.Integer scope) {
		set("scope", scope);
	}

	public java.lang.Integer getScope() {
		return get("scope");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setFull(java.math.BigDecimal full) {
		set("full", full);
	}

	public java.math.BigDecimal getFull() {
		return get("full");
	}

	public void setValue(java.math.BigDecimal value) {
		set("value", value);
	}

	public java.math.BigDecimal getValue() {
		return get("value");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shopId", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shopId");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setShopName(java.lang.String shopName) {
		set("shopName", shopName);
	}

	public java.lang.String getShopName() {
		return get("shopName");
	}

}
