package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setStreet(java.lang.String street) {
		set("street", street);
	}

	public java.lang.String getStreet() {
		return get("street");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setPhone1(java.lang.String phone1) {
		set("phone1", phone1);
	}

	public java.lang.String getPhone1() {
		return get("phone1");
	}

	public void setPhone1Type(java.lang.String phone1Type) {
		set("phone1Type", phone1Type);
	}

	public java.lang.String getPhone1Type() {
		return get("phone1Type");
	}

	public void setPhone2(java.lang.String phone2) {
		set("phone2", phone2);
	}

	public java.lang.String getPhone2() {
		return get("phone2");
	}

	public void setPhone2Type(java.lang.String phone2Type) {
		set("phone2Type", phone2Type);
	}

	public java.lang.String getPhone2Type() {
		return get("phone2Type");
	}

	public void setPhone3(java.lang.String phone3) {
		set("phone3", phone3);
	}

	public java.lang.String getPhone3() {
		return get("phone3");
	}

	public void setPhone3Type(java.lang.String phone3Type) {
		set("phone3Type", phone3Type);
	}

	public java.lang.String getPhone3Type() {
		return get("phone3Type");
	}

	public void setContactPerson(java.lang.String contactPerson) {
		set("contactPerson", contactPerson);
	}

	public java.lang.String getContactPerson() {
		return get("contactPerson");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("district_id", districtId);
	}

	public java.lang.Integer getDistrictId() {
		return get("district_id");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setCreateProvince(java.lang.String createProvince) {
		set("createProvince", createProvince);
	}

	public java.lang.String getCreateProvince() {
		return get("createProvince");
	}

	public void setCreateCity(java.lang.String createCity) {
		set("createCity", createCity);
	}

	public java.lang.String getCreateCity() {
		return get("createCity");
	}

	public void setCreateBank(java.lang.String createBank) {
		set("createBank", createBank);
	}

	public java.lang.String getCreateBank() {
		return get("createBank");
	}

	public void setCreateName(java.lang.String createName) {
		set("createName", createName);
	}

	public java.lang.String getCreateName() {
		return get("createName");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bankAccount", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return get("bankAccount");
	}

	public void setSupplierContractId(java.lang.Integer supplierContractId) {
		set("supplier_contract_id", supplierContractId);
	}

	public java.lang.Integer getSupplierContractId() {
		return get("supplier_contract_id");
	}

	public void setLegalPerson(java.lang.String legalPerson) {
		set("legalPerson", legalPerson);
	}

	public java.lang.String getLegalPerson() {
		return get("legalPerson");
	}

	public void setFixedTelephone(java.lang.String fixedTelephone) {
		set("fixedTelephone", fixedTelephone);
	}

	public java.lang.String getFixedTelephone() {
		return get("fixedTelephone");
	}

}
