package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionSku<M extends BasePromotionSku<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setPriceId(java.lang.Integer priceId) {
		set("price_id", priceId);
	}

	public java.lang.Integer getPriceId() {
		return get("price_id");
	}

	public void setPromotionPrice(java.math.BigDecimal promotionPrice) {
		set("promotion_price", promotionPrice);
	}

	public java.math.BigDecimal getPromotionPrice() {
		return get("promotion_price");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setLimitStock(java.lang.Integer limitStock) {
		set("limit_stock", limitStock);
	}

	public java.lang.Integer getLimitStock() {
		return get("limit_stock");
	}

	public void setPromotionId(java.lang.Integer promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Integer getPromotionId() {
		return get("promotion_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setSelectProterties(java.lang.String selectProterties) {
		set("selectProterties", selectProterties);
	}

	public java.lang.String getSelectProterties() {
		return get("selectProterties");
	}

}
