package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupSetMeals<M extends BaseGroupSetMeals<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}

	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setGroupActivityId(java.lang.Integer groupActivityId) {
		set("group_activity_id", groupActivityId);
	}

	public java.lang.Integer getGroupActivityId() {
		return get("group_activity_id");
	}

	public void setStoreAmount(java.lang.Integer storeAmount) {
		set("store_amount", storeAmount);
	}

	public java.lang.Integer getStoreAmount() {
		return get("store_amount");
	}

	public void setIsSale(java.lang.String isSale) {
		set("is_sale", isSale);
	}

	public java.lang.String getIsSale() {
		return get("is_sale");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

}
