package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBigOrders<M extends BaseBigOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return get("source");
	}

	public void setPreferredContactPhone(java.lang.String preferredContactPhone) {
		set("preferredContactPhone", preferredContactPhone);
	}

	public java.lang.String getPreferredContactPhone() {
		return get("preferredContactPhone");
	}

	public void setTotalPayable(java.math.BigDecimal totalPayable) {
		set("totalPayable", totalPayable);
	}

	public java.math.BigDecimal getTotalPayable() {
		return get("totalPayable");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("orderTime", orderTime);
	}

	public java.util.Date getOrderTime() {
		return get("orderTime");
	}

	public void setCompleteTime(java.util.Date completeTime) {
		set("completeTime", completeTime);
	}

	public java.util.Date getCompleteTime() {
		return get("completeTime");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}

	public java.lang.String getOrderCode() {
		return get("order_code");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setReceiveDetailAddress(java.lang.String receiveDetailAddress) {
		set("receiveDetailAddress", receiveDetailAddress);
	}

	public java.lang.String getReceiveDetailAddress() {
		return get("receiveDetailAddress");
	}

	public void setCancelReason(java.lang.String cancelReason) {
		set("cancel_reason", cancelReason);
	}

	public java.lang.String getCancelReason() {
		return get("cancel_reason");
	}

	public void setCancelNote(java.lang.String cancelNote) {
		set("cancel_note", cancelNote);
	}

	public java.lang.String getCancelNote() {
		return get("cancel_note");
	}

	public void setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

	public void setReceiveName(java.lang.String receiveName) {
		set("receiveName", receiveName);
	}

	public java.lang.String getReceiveName() {
		return get("receiveName");
	}

	public void setReceiveProvince(java.lang.String receiveProvince) {
		set("receiveProvince", receiveProvince);
	}

	public java.lang.String getReceiveProvince() {
		return get("receiveProvince");
	}

	public void setReceiveCity(java.lang.String receiveCity) {
		set("receiveCity", receiveCity);
	}

	public java.lang.String getReceiveCity() {
		return get("receiveCity");
	}

	public void setReceiveDistrict(java.lang.String receiveDistrict) {
		set("receiveDistrict", receiveDistrict);
	}

	public java.lang.String getReceiveDistrict() {
		return get("receiveDistrict");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("tradeNo", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("tradeNo");
	}

	public void setPayTime(java.util.Date payTime) {
		set("payTime", payTime);
	}

	public java.util.Date getPayTime() {
		return get("payTime");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancelTime", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancelTime");
	}

	public void setShopName(java.lang.String shopName) {
		set("shopName", shopName);
	}

	public java.lang.String getShopName() {
		return get("shopName");
	}

}
