package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderInvoice<M extends BaseOrderInvoice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customerId");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setInvoiceHead(java.lang.String invoiceHead) {
		set("invoiceHead", invoiceHead);
	}

	public java.lang.String getInvoiceHead() {
		return get("invoiceHead");
	}

	public void setInvoiceContent(java.lang.String invoiceContent) {
		set("invoiceContent", invoiceContent);
	}

	public java.lang.String getInvoiceContent() {
		return get("invoiceContent");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setAddressDetail(java.lang.String addressDetail) {
		set("addressDetail", addressDetail);
	}

	public java.lang.String getAddressDetail() {
		return get("addressDetail");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("companyName");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
	}

	public java.lang.String getCompanyCode() {
		return get("companyCode");
	}

	public void setCompanyAddress(java.lang.String companyAddress) {
		set("companyAddress", companyAddress);
	}

	public java.lang.String getCompanyAddress() {
		return get("companyAddress");
	}

	public void setCompanyPhone(java.lang.String companyPhone) {
		set("companyPhone", companyPhone);
	}

	public java.lang.String getCompanyPhone() {
		return get("companyPhone");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bankAccount", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return get("bankAccount");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("orderCode", orderCode);
	}

	public java.lang.String getOrderCode() {
		return get("orderCode");
	}

	public void setTotalPayable(java.math.BigDecimal totalPayable) {
		set("totalPayable", totalPayable);
	}

	public java.math.BigDecimal getTotalPayable() {
		return get("totalPayable");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setDistrict(java.lang.String district) {
		set("district", district);
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public void setTheSameOrderNum(java.lang.String theSameOrderNum) {
		set("theSameOrderNum", theSameOrderNum);
	}

	public java.lang.String getTheSameOrderNum() {
		return get("theSameOrderNum");
	}

}
