package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVatInvoiceItem<M extends BaseVatInvoiceItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("provinceId");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}

	public void setDistrictId(java.lang.Integer districtId) {
		set("districtId", districtId);
	}

	public java.lang.Integer getDistrictId() {
		return get("districtId");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setDistrict(java.lang.String district) {
		set("district", district);
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customerId", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customerId");
	}

	public void setAddressDetail(java.lang.String addressDetail) {
		set("addressDetail", addressDetail);
	}

	public java.lang.String getAddressDetail() {
		return get("addressDetail");
	}

}
