package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
	}

	public java.lang.String getMsgContent() {
		return get("msg_content");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setMsgGrade(java.lang.Integer msgGrade) {
		set("msg_grade", msgGrade);
	}

	public java.lang.Integer getMsgGrade() {
		return get("msg_grade");
	}

	public void setIsRead(java.lang.Integer isRead) {
		set("isRead", isRead);
	}

	public java.lang.Integer getIsRead() {
		return get("isRead");
	}

}
