package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBankCard<M extends BaseBankCard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setAccoutNumber(java.lang.String accoutNumber) {
		set("accoutNumber", accoutNumber);
	}

	public java.lang.String getAccoutNumber() {
		return get("accoutNumber");
	}

	public void setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
	}

	public java.lang.String getAccountName() {
		return get("accountName");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setBankBranch(java.lang.String bankBranch) {
		set("bankBranch", bankBranch);
	}

	public java.lang.String getBankBranch() {
		return get("bankBranch");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setContactNumber(java.lang.String contactNumber) {
		set("contactNumber", contactNumber);
	}

	public java.lang.String getContactNumber() {
		return get("contactNumber");
	}

}
