package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerPointRule<M extends BaseCustomerPointRule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.Integer code) {
		set("code", code);
	}

	public java.lang.Integer getCode() {
		return get("code");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setOriginal(java.math.BigDecimal original) {
		set("original", original);
	}

	public java.math.BigDecimal getOriginal() {
		return get("original");
	}

	public void setTarget(java.math.BigDecimal target) {
		set("target", target);
	}

	public java.math.BigDecimal getTarget() {
		return get("target");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

}
