package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerPoint<M extends BaseCustomerPoint<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return get("customer_id");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return get("source");
	}

	public void setRelateId(java.lang.Integer relateId) {
		set("relate_id", relateId);
	}

	public java.lang.Integer getRelateId() {
		return get("relate_id");
	}

	public void setCycleNum(java.lang.Integer cycleNum) {
		set("cycleNum", cycleNum);
	}

	public java.lang.Integer getCycleNum() {
		return get("cycleNum");
	}

}
