package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductOrder<M extends BaseProductOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setPricingUnit(java.lang.String pricingUnit) {
		set("pricingUnit", pricingUnit);
	}

	public java.lang.String getPricingUnit() {
		return get("pricingUnit");
	}

	public void setUnitOrdered(java.lang.Integer unitOrdered) {
		set("unitOrdered", unitOrdered);
	}

	public java.lang.Integer getUnitOrdered() {
		return get("unitOrdered");
	}

	public void setUnitCost(java.math.BigDecimal unitCost) {
		set("unitCost", unitCost);
	}

	public java.math.BigDecimal getUnitCost() {
		return get("unitCost");
	}

	public void setSuggestedRetailUnitPrice(java.math.BigDecimal suggestedRetailUnitPrice) {
		set("suggestedRetailUnitPrice", suggestedRetailUnitPrice);
	}

	public java.math.BigDecimal getSuggestedRetailUnitPrice() {
		return get("suggestedRetailUnitPrice");
	}

	public void setActualUnitPrice(java.math.BigDecimal actualUnitPrice) {
		set("actualUnitPrice", actualUnitPrice);
	}

	public java.math.BigDecimal getActualUnitPrice() {
		return get("actualUnitPrice");
	}

	public void setTotalProductCost(java.math.BigDecimal totalProductCost) {
		set("totalProductCost", totalProductCost);
	}

	public java.math.BigDecimal getTotalProductCost() {
		return get("totalProductCost");
	}

	public void setTotalDeliveryCost(java.math.BigDecimal totalDeliveryCost) {
		set("totalDeliveryCost", totalDeliveryCost);
	}

	public java.math.BigDecimal getTotalDeliveryCost() {
		return get("totalDeliveryCost");
	}

	public void setTotalCost(java.math.BigDecimal totalCost) {
		set("totalCost", totalCost);
	}

	public java.math.BigDecimal getTotalCost() {
		return get("totalCost");
	}

	public void setTotalActualProductPrice(java.math.BigDecimal totalActualProductPrice) {
		set("totalActualProductPrice", totalActualProductPrice);
	}

	public java.math.BigDecimal getTotalActualProductPrice() {
		return get("totalActualProductPrice");
	}

	public void setTotalActualDeliveryCharge(java.math.BigDecimal totalActualDeliveryCharge) {
		set("totalActualDeliveryCharge", totalActualDeliveryCharge);
	}

	public java.math.BigDecimal getTotalActualDeliveryCharge() {
		return get("totalActualDeliveryCharge");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("totalPrice", totalPrice);
	}

	public java.math.BigDecimal getTotalPrice() {
		return get("totalPrice");
	}

	public void setSelectProterties(java.lang.String selectProterties) {
		set("selectProterties", selectProterties);
	}

	public java.lang.String getSelectProterties() {
		return get("selectProterties");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
	}

	public java.lang.String getSupplierName() {
		return get("supplier_name");
	}

	public void setUpc(java.lang.String upc) {
		set("upc", upc);
	}

	public java.lang.String getUpc() {
		return get("upc");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("category_name", categoryName);
	}

	public java.lang.String getCategoryName() {
		return get("category_name");
	}

	public void setProductSummary(java.lang.String productSummary) {
		set("product_summary", productSummary);
	}

	public java.lang.String getProductSummary() {
		return get("product_summary");
	}

	public void setPriceId(java.lang.Integer priceId) {
		set("priceId", priceId);
	}

	public java.lang.Integer getPriceId() {
		return get("priceId");
	}

	public void setTaxName(java.lang.String taxName) {
		set("taxName", taxName);
	}

	public java.lang.String getTaxName() {
		return get("taxName");
	}

	public void setTaxRate(java.math.BigDecimal taxRate) {
		set("taxRate", taxRate);
	}

	public java.math.BigDecimal getTaxRate() {
		return get("taxRate");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("couponDiscount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("couponDiscount");
	}

	public void setPromotionId(java.lang.Integer promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Integer getPromotionId() {
		return get("promotion_id");
	}

	public void setIsGift(java.lang.Integer isGift) {
		set("isGift", isGift);
	}

	public java.lang.Integer getIsGift() {
		return get("isGift");
	}

	public void setTaxRateSum(java.math.BigDecimal taxRateSum) {
		set("taxRateSum", taxRateSum);
	}

	public java.math.BigDecimal getTaxRateSum() {
		return get("taxRateSum");
	}

	public void setInvoiceType(java.lang.String invoiceType) {
		set("invoiceType", invoiceType);
	}

	public java.lang.String getInvoiceType() {
		return get("invoiceType");
	}

	public void setUnitCostNoTax(java.math.BigDecimal unitCostNoTax) {
		set("unitCostNoTax", unitCostNoTax);
	}

	public java.math.BigDecimal getUnitCostNoTax() {
		return get("unitCostNoTax");
	}

	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}

	public java.lang.Integer getOrderType() {
		return get("order_type");
	}

	public void setCommission(java.math.BigDecimal commission) {
		set("commission", commission);
	}

	public java.math.BigDecimal getCommission() {
		return get("commission");
	}

}
