package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductPrice<M extends BaseProductPrice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setTypeAttr(java.lang.String typeAttr) {
		set("type_attr", typeAttr);
	}

	public java.lang.String getTypeAttr() {
		return get("type_attr");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setWeight(java.lang.Double weight) {
		set("weight", weight);
	}

	public java.lang.Double getWeight() {
		return get("weight");
	}

	public void setProductNumber(java.lang.Integer productNumber) {
		set("product_number", productNumber);
	}

	public java.lang.Integer getProductNumber() {
		return get("product_number");
	}

	public void setAlertNumber(java.lang.Integer alertNumber) {
		set("alert_number", alertNumber);
	}

	public java.lang.Integer getAlertNumber() {
		return get("alert_number");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}

	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public void setOriginUnitPrice(java.math.BigDecimal originUnitPrice) {
		set("originUnitPrice", originUnitPrice);
	}

	public java.math.BigDecimal getOriginUnitPrice() {
		return get("originUnitPrice");
	}

	public void setUnitCost(java.math.BigDecimal unitCost) {
		set("unitCost", unitCost);
	}

	public java.math.BigDecimal getUnitCost() {
		return get("unitCost");
	}

	public void setUnitCostNoTax(java.math.BigDecimal unitCostNoTax) {
		set("unitCostNoTax", unitCostNoTax);
	}

	public java.math.BigDecimal getUnitCostNoTax() {
		return get("unitCostNoTax");
	}

}
