package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductTrip<M extends BaseProductTrip<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setUnitCost(java.math.BigDecimal unitCost) {
		set("unitCost", unitCost);
	}

	public java.math.BigDecimal getUnitCost() {
		return get("unitCost");
	}

	public void setProductNumber(java.lang.Integer productNumber) {
		set("product_number", productNumber);
	}

	public java.lang.Integer getProductNumber() {
		return get("product_number");
	}

	public void setStartAt(java.util.Date startAt) {
		set("start_at", startAt);
	}

	public java.util.Date getStartAt() {
		return get("start_at");
	}

	public void setEndAt(java.util.Date endAt) {
		set("end_at", endAt);
	}

	public java.util.Date getEndAt() {
		return get("end_at");
	}

	public void setOriginUnitPrice(java.math.BigDecimal originUnitPrice) {
		set("originUnitPrice", originUnitPrice);
	}

	public java.math.BigDecimal getOriginUnitPrice() {
		return get("originUnitPrice");
	}

}
