package com.eshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierBillItem<M extends BaseSupplierBillItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProductOrderId(java.lang.Integer productOrderId) {
		set("product_order_id", productOrderId);
	}

	public java.lang.Integer getProductOrderId() {
		return get("product_order_id");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setSupplierName(java.lang.String supplierName) {
		set("supplier_name", supplierName);
	}

	public java.lang.String getSupplierName() {
		return get("supplier_name");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setPriceId(java.lang.Integer priceId) {
		set("priceId", priceId);
	}

	public java.lang.Integer getPriceId() {
		return get("priceId");
	}

	public void setSelectProterties(java.lang.String selectProterties) {
		set("selectProterties", selectProterties);
	}

	public java.lang.String getSelectProterties() {
		return get("selectProterties");
	}

	public void setTaxRate(java.math.BigDecimal taxRate) {
		set("taxRate", taxRate);
	}

	public java.math.BigDecimal getTaxRate() {
		return get("taxRate");
	}

	public void setUnitOrdered(java.lang.Integer unitOrdered) {
		set("unitOrdered", unitOrdered);
	}

	public java.lang.Integer getUnitOrdered() {
		return get("unitOrdered");
	}

	public void setUnitCost(java.math.BigDecimal unitCost) {
		set("unitCost", unitCost);
	}

	public java.math.BigDecimal getUnitCost() {
		return get("unitCost");
	}

	public void setSuggestedRetailUnitPrice(java.math.BigDecimal suggestedRetailUnitPrice) {
		set("suggestedRetailUnitPrice", suggestedRetailUnitPrice);
	}

	public java.math.BigDecimal getSuggestedRetailUnitPrice() {
		return get("suggestedRetailUnitPrice");
	}

	public void setActualUnitPrice(java.math.BigDecimal actualUnitPrice) {
		set("actualUnitPrice", actualUnitPrice);
	}

	public java.math.BigDecimal getActualUnitPrice() {
		return get("actualUnitPrice");
	}

	public void setTotalProductCost(java.math.BigDecimal totalProductCost) {
		set("totalProductCost", totalProductCost);
	}

	public java.math.BigDecimal getTotalProductCost() {
		return get("totalProductCost");
	}

	public void setTotalActualProductPrice(java.math.BigDecimal totalActualProductPrice) {
		set("totalActualProductPrice", totalActualProductPrice);
	}

	public java.math.BigDecimal getTotalActualProductPrice() {
		return get("totalActualProductPrice");
	}

	public void setSendOutTime(java.util.Date sendOutTime) {
		set("sendOutTime", sendOutTime);
	}

	public java.util.Date getSendOutTime() {
		return get("sendOutTime");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}

	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public void setAuditedAt(java.util.Date auditedAt) {
		set("audited_at", auditedAt);
	}

	public java.util.Date getAuditedAt() {
		return get("audited_at");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setSupplierBillId(java.lang.Integer supplierBillId) {
		set("supplier_bill_id", supplierBillId);
	}

	public java.lang.Integer getSupplierBillId() {
		return get("supplier_bill_id");
	}

	public void setTradeType(java.lang.String tradeType) {
		set("tradeType", tradeType);
	}

	public java.lang.String getTradeType() {
		return get("tradeType");
	}

	public void setUnitCostNoTax(java.math.BigDecimal unitCostNoTax) {
		set("unitCostNoTax", unitCostNoTax);
	}

	public java.math.BigDecimal getUnitCostNoTax() {
		return get("unitCostNoTax");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}

	public java.lang.String getOrderCode() {
		return get("order_code");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

}
