package com.eshop.model;

import com.eshop.model.base.BaseHelpLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HelpLink extends BaseHelpLink<HelpLink> {
	public static final HelpLink dao = new HelpLink();
}
