package com.eshop.model;

import com.eshop.model.base.BaseProductTrip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductTrip extends BaseProductTrip<ProductTrip> {
	public static final ProductTrip dao = new ProductTrip();
}
