package com.eshop.model;

import com.eshop.model.base.BasePromotionMansong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionMansong extends BasePromotionMansong<PromotionMansong> {
	public static final PromotionMansong dao = new PromotionMansong();
}
