package com.eshop.model;

import com.eshop.model.base.BaseLogRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogRecord extends BaseLogRecord<LogRecord> {
	public static final LogRecord dao = new LogRecord();
}
