package com.eshop.model;

import com.eshop.model.base.BasePromotionDazhe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionDazhe extends BasePromotionDazhe<PromotionDazhe> {
	public static final PromotionDazhe dao = new PromotionDazhe();
}
