package com.eshop.model;

import com.eshop.model.base.BaseCustomerGrowth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerGrowth extends BaseCustomerGrowth<CustomerGrowth> {
	public static final CustomerGrowth dao = new CustomerGrowth();
}
