package com.eshop.model;

import com.eshop.model.base.BaseProductHotel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductHotel extends BaseProductHotel<ProductHotel> {
	public static final ProductHotel dao = new ProductHotel();
}
