package com.eshop.model;

import com.eshop.model.base.BaseRecommendPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecommendPosition extends BaseRecommendPosition<RecommendPosition> {
	public static final RecommendPosition dao = new RecommendPosition();
}
