package com.eshop.model;

import com.eshop.model.base.BaseGroupProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupProducts extends BaseGroupProducts<GroupProducts> {
	public static final GroupProducts dao = new GroupProducts();
}
