package com.eshop.model;

import com.eshop.model.base.BasePointProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointProduct extends BasePointProduct<PointProduct> {
	public static final PointProduct dao = new PointProduct();
}
