package com.eshop.model;

import com.eshop.model.base.BaseVatInvoiceItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VatInvoiceItem extends BaseVatInvoiceItem<VatInvoiceItem> {
	public static final VatInvoiceItem dao = new VatInvoiceItem();
}
